package dev.fenix.ui.theme.token.color_scheme

import androidx.compose.ui.graphics.Color

object Colors {

    object Light {
        val primary = Color(0xFFE30C52)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFE60057)
        val onPrimaryContainer = Color(0xFFFFFBFF)
        val secondary = Color(0xFFAC2E4C)
        val onSecondary = Color(0xFFFFFFFF)
        val secondaryContainer = Color(0xFFFF6D89)
        val onSecondaryContainer = Color(0xFF700026)
        val tertiary = Color(0xFF9E3D00)
        val onTertiary = Color(0xFFFFFFFF)
        val tertiaryContainer = Color(0xFFC64F00)
        val onTertiaryContainer = Color(0xFFFFFBFF)
        val error = Color(0xFFBA1A1A)
        val errorContainer = Color(0xFFFFDAD6)
        val onError = Color(0xFFFFFFFF)
        val onErrorContainer = Color(0xFF93000A)
        val background = Color(0xFFEFEFEF)
        val onBackground = Color(0xFF281719)
        val surface = Color(0xFFFFF8F7)
        val onSurface = Color(0xFF211E1E)
        val surfaceVariant = Color(0xFFFFD9DD)
        val onSurfaceVariant = Color(0xFF5C3F43)
        val outline = Color(0xFF916E72)
        val inverseOnSurface = Color(0xFFFFECED)
        val inverseSurface = Color(0xFF3F2B2D)
        val inversePrimary = Color(0xFFFFB2BC)
        val surfaceTint = Color(0xFFB80044)
        val outlineVariant = Color(0xFFE5BCC0)
        val scrim = Color(0xFF000000)
    }

    object Dark {
        val primary = Color(0xFF96424D)
        val onPrimary = Color(0xFF670022)
        val primaryContainer = Color(0xFFFF4F77)
        val onPrimaryContainer = Color(0xFF3A0010)
        val secondary = Color(0xFFFFB2BC)
        val onSecondary = Color(0xFF670022)
        val secondaryContainer = Color(0xFF522B35)
        val onSecondaryContainer = Color(0xFFFF9CAA)
        val tertiary = Color(0xFFFFB695)
        val onTertiary = Color(0xFF571E00)
        val tertiaryContainer = Color(0xFFF06717)
        val onTertiaryContainer = Color(0xFF310E00)
        val error = Color(0xFFFFB4AB)
        val errorContainer = Color(0xFF93000A)
        val onError = Color(0xFF690005)
        val onErrorContainer = Color(0xFFFFDAD6)
        val background = Color(0xFF170B0C)
        val onBackground = Color(0xFFFBDBDD)
        val surface = Color(0xFF1F0F11)
        val onSurface = Color(0xFFFBDBDD)
        val surfaceVariant = Color(0xFF5C3F43)
        val onSurfaceVariant = Color(0xFFE5BCC0)
        val outline = Color(0xFFAC878B)
        val inverseOnSurface = Color(0xFF3F2B2D)
        val inverseSurface = Color(0xFFFBDBDD)
        val inversePrimary = Color(0xFFBD0046)
        val surfaceTint = Color(0xFFFFB2BC)
        val outlineVariant = Color(0xFF5C3F43)
        val scrim = Color(0xFF000000)
    }
}