package dev.fenix.ui.theme.token.color_scheme

import androidx.compose.ui.graphics.Color

object Colors {

    object Light {
        val primary = Color(0xFFE91E63)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFFFDDB3)
        val onPrimaryContainer = Color(0xFF291800)
        val secondary = Color(0xFF6F5B40)
        val onSecondary = Color(0xFFFFFFFF)
        val secondaryContainer = Color(0xFFFBDEBC)
        val onSecondaryContainer = Color(0xFF271904)
        val tertiary = Color(0xFF51643F)
        val onTertiary = Color(0xFFFFFFFF)
        val tertiaryContainer = Color(0xFFD4EABB)
        val onTertiaryContainer = Color(0xFF102004)
        val error = Color(0xFFBA1A1A)
        val errorContainer = Color(0xFFFFDAD6)
        val onError = Color(0xFFFFFFFF)
        val onErrorContainer = Color(0xFF410002)
        val background = Color(0xFFFFFBFF)
        val onBackground = Color(0xFF1F1B16)
        val surface = Color(0xFFFFFBFF)
        val onSurface = Color(0xFF1F1B16)
        val surfaceVariant = Color(0xFFF0E0CF)
        val onSurfaceVariant = Color(0xFF4F4539)
        val outline = Color(0xFF817567)
        val inverseOnSurface = Color(0xFFF9EFE7)
        val inverseSurface = Color(0xFF34302A)
        val inversePrimary = Color(0xFFFFB951)
        val surfaceTint = Color(0xFF825500)
        val outlineVariant = Color(0xFFD3C4B4)
        val scrim = Color(0xFF000000)
    }

    object Dark {
        val primary = Color(0xFFA92352)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFF633F00)
        val onPrimaryContainer = Color(0xFFFFDDB3)
        val secondary = Color(0xFFDDC2A1)
        val onSecondary = Color(0xFF3E2D16)
        val secondaryContainer = Color(0xFF56442A)
        val onSecondaryContainer = Color(0xFFFBDEBC)
        val tertiary = Color(0xFFB8CEA1)
        val onTertiary = Color(0xFF243515)
        val tertiaryContainer = Color(0xFF3A4C2A)
        val onTertiaryContainer = Color(0xFFD4EABB)
        val error = Color(0xFFFFB4AB)
        val errorContainer = Color(0xFF93000A)
        val onError = Color(0xFF690005)
        val onErrorContainer = Color(0xFFFFDAD6)
        val background = Color(0xFF151515)
        val onBackground = Color(0xFFEAE1D9)
        val surface = Color(0xFF1F1B16)
        val onSurface = Color(0xFFEAE1D9)
        val surfaceVariant = Color(0xFF4F4539)
        val onSurfaceVariant = Color(0xFFD3C4B4)
        val outline = Color(0xFF9C8F80)
        val inverseOnSurface = Color(0xFF1F1B16)
        val inverseSurface = Color(0xFFEAE1D9)
        val inversePrimary = Color(0xFF825500)
        val surfaceTint = Color(0xFFFFB951)
        val outlineVariant = Color(0xFF4F4539)
        val scrim = Color(0xFF000000)
    }
}